version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: kazemi3
    restart: unless-stopped
    environment:
      - NODE_ENV=productiona
      - PORT=3000
      - MONGO_URL=env
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"


  mongo:
    image: mongo:5.0
    container_name: mongo-dev
    restart: always
    networks:
      - -network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
